// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // With Prisma 7, the URL is provided here if not in schema for some commands,
    // but the Client will mainly use the adapter.
    // However, for migration commands which might use this config:
    url: process.env.POSTGRES_PRISMA_URL || process.env.DATABASE_URL || "file:./dev.db",
  },
});
